import sources from "../data/sources.json" with { type: "json" };

const recipes = [
  [
    "chicken-broccoli",
    "西兰花炒鸡胸肉",
    "chickenBroccoli",
    ["breast", "broccoli"],
    20,
    ["wok"],
    true,
    [
      ["breast", 150, "g"],
      ["broccoli", 250, "g"],
    ],
    ["生抽 5ml", "蒜 2瓣", "淀粉 3g", "油 5g"],
    [
      "鸡胸切薄片，用生抽、淀粉和一小勺水抓匀，冷藏腌10分钟。",
      "西兰花切小朵，茎切薄片，焯至刚熟后沥水。",
      "热锅加油，下蒜末和鸡肉，分散炒熟。",
      "加入西兰花拌匀，鸡肉中心达到74℃后出锅。",
    ],
  ],
  [
    "chicken-mushroom",
    "黑椒口蘑鸡胸",
    "chickenMushroom",
    ["breast", "mushroom"],
    20,
    ["wok"],
    true,
    [
      ["breast", 150, "g"],
      ["mushroom", 250, "g"],
    ],
    ["黑胡椒 少许", "生抽 5ml", "蒜 2瓣", "油 5g"],
    [
      "鸡胸切成约1cm厚的片，口蘑切厚片。",
      "鸡肉加生抽、胡椒和少量水抓匀，冷藏腌10分钟。",
      "锅中加油，先煎熟鸡肉盛出，再炒口蘑至软。",
      "鸡肉回锅拌匀，确认中心74℃，少留汤汁。",
    ],
  ],
  [
    "chicken-three",
    "西兰花口蘑鸡丁",
    "chickenThree",
    ["breast", "broccoli", "mushroom"],
    25,
    ["wok"],
    true,
    [
      ["breast", 150, "g"],
      ["broccoli", 150, "g"],
      ["mushroom", 150, "g"],
    ],
    ["生抽 5ml", "淀粉 3g", "黑胡椒 少许", "油 5g"],
    [
      "鸡胸切丁，加入生抽、淀粉和一小勺水腌10分钟。",
      "西兰花焯熟沥水；口蘑切片。",
      "锅内少油炒鸡丁至熟，放入口蘑继续翻炒。",
      "最后加入西兰花，拌匀并检查鸡肉中心至少74℃。",
    ],
  ],
  [
    "air-chicken",
    "蒜香鸡胸时蔬盘",
    "chickenPotato",
    ["breast", "broccoli", "potato"],
    30,
    ["air-fryer"],
    true,
    [
      ["breast", 150, "g"],
      ["broccoli", 200, "g"],
      ["potato", 150, "g"],
    ],
    ["蒜 2瓣", "黑胡椒 少许", "盐 少许", "油 5g"],
    [
      "鸡胸片薄，土豆切成约2cm的小块，分别拌上调味和少量油。",
      "土豆先入空气炸锅，180℃烤约10分钟。",
      "鸡肉单层加入，继续烤约12至15分钟，中途翻面检查。",
      "西兰花另外蒸熟或焯熟。鸡肉中心至少74℃，土豆软透后合盘。",
    ],
  ],
  [
    "chicken-asparagus",
    "芦笋滑炒鸡柳",
    "chickenAsparagus",
    ["breast", "asparagus"],
    20,
    ["wok"],
    true,
    [
      ["breast", 150, "g"],
      ["asparagus", 250, "g"],
    ],
    ["生抽 5ml", "淀粉 3g", "蒜 2瓣", "油 5g"],
    [
      "鸡胸逆纹切条，拌入生抽、淀粉和少量水。",
      "芦笋去老根切段，粗段先焯一下。",
      "热锅薄油滑炒鸡柳，加入芦笋继续炒。",
      "鸡肉中心达到74℃，芦笋熟透后调味出锅。",
    ],
  ],
  [
    "shrimp-asparagus",
    "芦笋炒虾仁",
    "shrimpAsparagus",
    ["shrimp", "asparagus"],
    15,
    ["wok"],
    true,
    [
      ["shrimp", 150, "g"],
      ["asparagus", 250, "g"],
    ],
    ["蒜 2瓣", "盐 少许", "黑胡椒 少许", "油 5g"],
    [
      "虾仁按包装冷藏解冻、沥水，芦笋去老根切段。",
      "较粗的芦笋先焯至接近熟，沥干。",
      "热锅少油炒蒜末，下虾仁，再放芦笋。",
      "虾仁通体不透明、肉质紧实，蔬菜熟透后出锅。",
    ],
  ],
  [
    "shrimp-mushroom",
    "蒜香口蘑虾仁",
    "shrimpMushroom",
    ["shrimp", "mushroom"],
    20,
    ["wok"],
    true,
    [
      ["shrimp", 150, "g"],
      ["mushroom", 250, "g"],
    ],
    ["蒜 3瓣", "生抽 5ml", "黑胡椒 少许", "油 5g"],
    [
      "虾仁解冻沥水，白蘑菇切片，蒜切末。",
      "锅中加油，先把蘑菇炒软，加入蒜末。",
      "放入虾仁和生抽翻炒，必要时加一小勺水。",
      "虾仁炒至完全不透明，收至少量汁水。",
    ],
  ],
  [
    "shrimp-broccoli",
    "西兰花虾仁",
    "shrimpBroccoli",
    ["shrimp", "broccoli"],
    15,
    ["wok"],
    true,
    [
      ["shrimp", 150, "g"],
      ["broccoli", 250, "g"],
    ],
    ["蒜 2瓣", "盐 少许", "油 5g"],
    [
      "西兰花切小朵焯熟，虾仁冷藏解冻后沥水。",
      "热锅少油炒香蒜末，再下虾仁。",
      "加入西兰花翻炒至虾仁完全熟透，轻调味。",
    ],
  ],
  [
    "steak-mushroom",
    "黑椒牛排配口蘑",
    "steakMushroom",
    ["steak", "mushroom", "onion"],
    25,
    ["wok"],
    false,
    [
      ["steak", 150, "g"],
      ["mushroom", 150, "g"],
      ["onion", 100, "g"],
    ],
    ["黑胡椒 少许", "盐 少许", "油 4g"],
    [
      "牛排按包装解冻，擦干；洋葱切丝、白蘑菇切片。",
      "热锅薄油煎牛排，原切牛排中心至少63℃，出锅静置3分钟。",
      "同锅炒熟洋葱和蘑菇，配牛排食用。调理、嫩化产品按包装充分加热。",
    ],
  ],
  [
    "rib-potato",
    "土豆洋葱焖牛肋条",
    "beefRib",
    ["rib", "potato", "onion", "carrot"],
    75,
    ["casserole", "pressure"],
    true,
    [
      ["rib", 150, "g"],
      ["potato", 150, "g"],
      ["onion", 100, "g"],
      ["carrot", 100, "g"],
    ],
    ["姜 3片", "生抽 8ml", "八角 1小块"],
    [
      "牛肋条去明显肥油、切块焯水；蔬菜切成适口块。",
      "珐琅锅放牛肉、姜、生抽、八角，加水盖过原料。",
      "小火焖至软，再加土豆、胡萝卜与洋葱，煮至全熟。",
      "高压锅按本机肉类程序、最低水量和装量操作，完全泄压后开盖；装盒少带浮油和汤汁。",
    ],
  ],
  [
    "shank-braised",
    "清卤牛腱配娃娃菜",
    "beefShank",
    ["shank", "baby", "carrot"],
    90,
    ["pressure", "casserole"],
    true,
    [
      ["shank", 150, "g"],
      ["baby", 200, "g"],
      ["carrot", 100, "g"],
    ],
    ["姜 3片", "八角 少许", "生抽 8ml"],
    [
      "牛腱焯水后，加姜、八角和生抽炖至软。批量做时所有用料按份数增加。",
      "高压锅按本机程序和装量使用，完全泄压后开盖。",
      "娃娃菜与胡萝卜另锅煮熟，沥水。",
      "牛腱熟后及时冷却，切片配菜；本份150g生肉通常约得100g熟肉，以实际出成率为准。",
    ],
  ],
  [
    "leg-braised",
    "卤鸡腿配胡萝卜",
    "braisedLeg",
    ["leg", "carrot"],
    40,
    ["casserole"],
    true,
    [
      ["leg", 250, "g"],
      ["carrot", 250, "g"],
    ],
    ["姜 3片", "生抽 8ml", "八角 少许"],
    [
      "本份鸡腿250g是带骨原料。用姜、生抽和八角煮开一锅卤水。",
      "加入鸡腿，小火煮约20至30分钟，中心至少74℃。",
      "胡萝卜切片另锅煮软；鸡腿去皮去骨后装盒。",
      "与牛腱共用卤汁时，先炖好牛腱，再用新鲜滚开的卤汁煮鸡腿。",
    ],
  ],
  [
    "chicken-choy",
    "菜心鸡胸糙米炒饭",
    "chickenChoy",
    ["breast", "choy", "carrot", "rice"],
    25,
    ["wok"],
    true,
    [
      ["breast", 150, "g"],
      ["choy", 200, "g"],
      ["carrot", 100, "g"],
      ["rice", 200, "g熟饭"],
    ],
    ["蒜 2瓣", "生抽 5ml", "油 5g"],
    [
      "鸡胸切丁，菜心和胡萝卜切碎，准备妥善冷藏或冷冻的熟糙米饭。",
      "热锅少油炒熟鸡丁与胡萝卜，加入菜心。",
      "加入熟饭炒散并充分热透，鸡肉与复热米饭中心均至少74℃。",
      "装盒后及时冷却，后半周份量当日冷冻。主料中的米饭按熟重称。",
    ],
  ],
  [
    "spinach-egg",
    "菠菜炒鸡蛋",
    "spinachEgg",
    ["spinach", "egg"],
    15,
    ["wok"],
    true,
    [
      ["spinach", 250, "g"],
      ["egg", 2, "个"],
    ],
    ["盐 少许", "油 5g"],
    [
      "菠菜洗净焯熟，沥干切段，鸡蛋打散。",
      "热锅少油，把蛋液炒至凝固。",
      "加入菠菜拌炒，鸡蛋完全凝固、菠菜热透后出锅。",
    ],
  ],
  [
    "baby-shrimp",
    "娃娃菜烩虾仁",
    "babyShrimp",
    ["baby", "shrimp"],
    20,
    ["wok", "casserole"],
    true,
    [
      ["baby", 250, "g"],
      ["shrimp", 150, "g"],
    ],
    ["蒜 2瓣", "生抽 5ml", "油 5g"],
    [
      "娃娃菜切段，虾仁按包装解冻沥水。",
      "锅中薄油炒蒜末，下娃娃菜炒软，加少量水。",
      "加入虾仁焖至熟透，虾肉应完全不透明，出锅前收至少量汁水。",
    ],
  ],
  [
    "yogurt-blueberry",
    "蓝莓酸奶碗",
    "yogurt",
    ["yogurt", "blueberry"],
    10,
    [],
    false,
    [
      ["yogurt", 270, "g"],
      ["blueberry", 150, "g"],
    ],
    [],
    [
      "冷冻蓝莓先确认包装食用要求；不确定是否可即食时，加热煮沸至少1分钟。",
      "将蓝莓快速冷却，再与两杯135g原味酸奶搭配。",
      "本份为酸奶早餐，可与蛋奶早餐轮换；酸奶的蛋白质含量以营养表为准。",
    ],
  ],
  [
    "leg-mushroom",
    "菌菇焖鸡腿",
    "legMushroom",
    ["leg", "mushroom", "onion"],
    35,
    ["casserole", "wok"],
    true,
    [
      ["leg", 250, "g"],
      ["mushroom", 200, "g"],
      ["onion", 100, "g"],
    ],
    ["姜 3片", "生抽 8ml", "油 4g"],
    [
      "鸡腿按带骨250g准备，蘑菇切厚片、洋葱切丝。",
      "锅中薄油炒洋葱和姜，下鸡腿翻炒，再加生抽与少量水。",
      "加入蘑菇，加盖小火焖至全熟，鸡肉中心至少74℃。",
      "装盒前去皮去骨，少带汤汁，及时冷却储存。",
    ],
  ],
];

export const catalog = recipes
  .filter((row) => sources[row[2]])
  .map(
    ([
      id,
      title,
      sourceKey,
      ingredientIds,
      minutes,
      equipment,
      prep,
      portions,
      seasonings,
      steps,
    ]) => {
      const source = sources[sourceKey];
      return {
        id,
        title,
        ingredientIds,
        minutes,
        equipment,
        prep,
        ingredients: portions.map(([id, amount, unit]) => ({
          id,
          amount,
          unit,
        })),
        seasonings,
        steps: steps.map((text, index) => ({ id: index + 1, text })),
        origin: "curated",
        source: "下厨房",
        sourceTitle: source.title,
        author: source.author || "",
        url: source.url,
        image: source.localImage || source.image,
        checkedAt: source.checkedAt,
        note: prep
          ? "熟饭菜及时浅份冷却。后半周份量当天冷冻，前夜冷藏解冻，复热中心至少74℃。"
          : "更适合现做现吃。份量为单人起点，按实际食欲和活动量调整。",
      };
    },
  );
