export const ingredients = [
  {
    id: "breast",
    name: "鸡胸肉",
    aliases: ["鸡胸", "鸡柳", "鸡小胸"],
    category: "protein",
    quantity: 2600,
    unit: "g",
  },
  {
    id: "leg",
    name: "琵琶腿",
    searchName: "鸡腿",
    aliases: ["鸡腿", "鸡上腿"],
    category: "protein",
    quantity: 2600,
    unit: "g",
  },
  {
    id: "shank",
    name: "牛腱心",
    searchName: "牛腱",
    aliases: ["牛腱", "牛展", "腱子"],
    category: "protein",
    quantity: 1500,
    unit: "g",
  },
  {
    id: "rib",
    name: "牛肋条",
    aliases: ["牛肋肉", "牛肋骨"],
    category: "protein",
    quantity: 2100,
    unit: "g",
  },
  {
    id: "steak",
    name: "牛排",
    aliases: ["西冷", "菲力", "板腱"],
    category: "protein",
    quantity: 10,
    unit: "份",
  },
  {
    id: "stirBeef",
    name: "黄牛嫩肉",
    searchName: "小炒黄牛肉",
    aliases: ["黄牛肉", "牛里脊", "嫩牛肉"],
    category: "protein",
    quantity: 0,
    unit: "g",
  },
  {
    id: "shrimp",
    name: "虾仁",
    aliases: ["鲜虾", "大虾", "白虾"],
    category: "protein",
    quantity: 900,
    unit: "g",
  },
  {
    id: "salmon",
    name: "三文鱼",
    aliases: ["鲑鱼"],
    category: "protein",
    quantity: 0,
    unit: "g",
  },
  {
    id: "mandarinFish",
    name: "鳜鱼",
    searchName: "清蒸鳜鱼",
    aliases: ["桂鱼"],
    category: "protein",
    quantity: 0,
    unit: "g",
  },
  {
    id: "egg",
    name: "鸡蛋",
    aliases: ["蛋液", "全蛋"],
    category: "protein",
    quantity: 14,
    unit: "个",
  },
  {
    id: "broccoli",
    name: "西兰花",
    aliases: ["西蓝花"],
    category: "vegetable",
    quantity: 600,
    unit: "g",
  },
  {
    id: "mushroom",
    name: "白蘑菇",
    searchName: "口蘑",
    aliases: ["口蘑", "蘑菇", "鲜菇"],
    category: "vegetable",
    quantity: 700,
    unit: "g",
  },
  {
    id: "shiitake",
    name: "鲜香菇",
    searchName: "香菇",
    aliases: ["香菇", "冬菇"],
    category: "vegetable",
    quantity: 0,
    unit: "g",
  },
  {
    id: "asparagus",
    name: "芦笋",
    aliases: [],
    category: "vegetable",
    quantity: 600,
    unit: "g",
  },
  {
    id: "choy",
    name: "菜心",
    aliases: ["广东菜心"],
    category: "vegetable",
    quantity: 600,
    unit: "g",
  },
  {
    id: "baby",
    name: "娃娃菜",
    aliases: [],
    category: "vegetable",
    quantity: 850,
    unit: "g",
  },
  {
    id: "spinach",
    name: "菠菜苗",
    searchName: "菠菜",
    aliases: ["菠菜"],
    category: "vegetable",
    quantity: 400,
    unit: "g",
  },
  {
    id: "carrot",
    name: "胡萝卜",
    aliases: ["红萝卜"],
    category: "vegetable",
    quantity: 1000,
    unit: "g",
  },
  {
    id: "onion",
    name: "洋葱",
    aliases: ["紫洋葱", "红洋葱"],
    category: "vegetable",
    quantity: 1800,
    unit: "g",
  },
  {
    id: "pepper",
    name: "青红椒",
    searchName: "辣椒",
    aliases: ["杭椒", "尖椒", "小米椒"],
    category: "vegetable",
    quantity: 0,
    unit: "g",
  },
  {
    id: "potato",
    name: "土豆",
    aliases: ["马铃薯"],
    category: "staple",
    quantity: 2500,
    unit: "g",
  },
  {
    id: "sweet",
    name: "红薯",
    aliases: ["地瓜", "板栗薯"],
    category: "staple",
    quantity: 1000,
    unit: "g",
  },
  {
    id: "rice",
    name: "三色糙米",
    searchName: "糙米",
    aliases: ["糙米", "米饭"],
    category: "staple",
    quantity: 2100,
    unit: "g",
  },
  {
    id: "yogurt",
    name: "无糖酸奶",
    searchName: "酸奶",
    aliases: ["酸奶"],
    category: "other",
    quantity: 1350,
    unit: "g",
  },
  {
    id: "blueberry",
    name: "冷冻蓝莓",
    searchName: "蓝莓",
    aliases: ["蓝莓"],
    category: "other",
    quantity: 1360,
    unit: "g",
  },
  {
    id: "milk",
    name: "牛奶",
    aliases: ["纯牛奶"],
    category: "other",
    quantity: 2000,
    unit: "ml",
  },
  {
    id: "oil",
    name: "牛油果油",
    aliases: ["食用油", "植物油"],
    category: "seasoning",
    quantity: 1000,
    unit: "ml",
  },
];
export const equipment = [
  { id: "wok", name: "铁锅" },
  { id: "air-fryer", name: "空气炸锅" },
  { id: "steamer", name: "蒸锅" },
  { id: "pressure", name: "高压锅" },
  { id: "casserole", name: "珐琅锅" },
];
export function identifyIngredients(text, list = ingredients) {
  return list
    .filter((item) =>
      [item.name, ...(item.aliases || [])].some((name) => text.includes(name)),
    )
    .map((item) => item.id);
}
